title: Supplementary Material
paper_title: "Vulnerabilities in Naval Systems: CVE Analysis and Practical Attack Triggering via AIS/ECDIS"
markdown: kramdown

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
    values:
      layout: default
